---
- name: Install the latest version of psmisc
  ansible.builtin.package:
    name:
      - psmisc
    state: latest

- name: Copy Files to update WebLogic
  tags: updatePatchWebLogic
  become: true
  become_user: "{{ user }}"
  get_url:
    url: "http://192.168.1.110/repositorios/weblogic12/p34991973_122130_Generic.zip"
    dest: "{{ patch_dir }}"

- name: Change owner and group to root
  file:  
    path: "{{ patch_dir }}p34991973_122130_Generic.zip"
    owner: "{{ user }}"
    group: "{{ user }}"
    
    
- name: Unarchive patch file
  tags: updatePatchWebLogic
  unarchive:
    remote_src: true
    src: "{{ patch_dir }}p34991973_122130_Generic.zip"
    dest: "{{ patch_dir }}"

- name: Precheck update WL 
  tags: updatePatchWebLogic
  become: true
  become_user: "{{ user }}"
  shell: source /home/{{ user }}/.bash_profile;cd /home/proves/WLS_SPB_12.2.1.3.230118/tools/spbat/generic/SPBAT;./spbat.sh -phase precheck -oracle_home {{ oracle_home }}
  register: precheck

- name: Precheck result
  tags: updatePatchWebLogic
  debug:
    msg: " {{ precheck }}"

- name: Apply Patch WL 
  tags: updatePatchWebLogic
  become: true
  become_user: "{{ user }}"
  shell: source /home/{{ user }}/.bash_profile;cd /home/proves/WLS_SPB_12.2.1.3.230118/tools/spbat/generic/SPBAT;./spbat.sh -phase apply -oracle_home {{ oracle_home }}
  register: update

- name: Apply Patch WL result
  tags: updatePatchWebLogic
  debug:
    msg: " {{ update }}"
